name: Copy APWorld source
description: Copies APWorld source to a given destination
inputs:
  apworld-path:
    description: The path to the APWorld folder or APWorld itself
    required: true
  apworld-name:
    description: The name of the APWorld. This should only be set if the folder storing your apworld in the repository isn't the same
    default: ""
  destination:
    description: The destination to copy the APWorld source to
    default: "archipelago/worlds"
outputs:
  apworld-name:
    description: The resolved name of the APWorld
    value: ${{ steps.name.outputs.apworld-name }}
runs:
  using: composite
  steps:
    - name: Determine apworld name
      id: name
      shell: bash
      run: |
        if [[ "${APWORLD_NAME}" == "" ]]; then
          if [[ "${APWORLD_PATH}" == *.apworld ]]; then
            echo "apworld-name=$(basename "${APWORLD_PATH}" .apworld)" >> $GITHUB_OUTPUT
          else
            echo "apworld-name=$(basename "${APWORLD_PATH}")" >> $GITHUB_OUTPUT
          fi
        else
          echo "apworld-name=${APWORLD_NAME}" >> $GITHUB_OUTPUT
        fi
      env:
        APWORLD_PATH: ${{ inputs.apworld-path }}
        APWORLD_NAME: ${{ inputs.apworld-name }}

    - name: Copy apworld in worlds
      shell: bash
      run: |
        if [[ "${APWORLD_PATH}" == *.apworld ]]; then
          unzip -q "${APWORLD_PATH}" -d ${DESTINATION}/
        else
          mkdir -p ${DESTINATION}/${APWORLD_NAME}
          rsync --exclude archipelago --exclude .git -ap ${APWORLD_PATH}/* ${DESTINATION}/${APWORLD_NAME}
        fi

      env:
        APWORLD_PATH: ${{ inputs.apworld-path }}
        APWORLD_NAME: ${{steps.name.outputs.apworld-name}}
        DESTINATION: ${{ inputs.destination }}
