name: Package apworld
description: Package an apworld for distribution
inputs:
  path:
    description: The path to the apworld's folder in the repo or apworld file itself
    required: true
  checkout:
    description: Whether or not to run the checkout step. Can be useful to disable if you want to package the apworld with a dirty repo
    default: true
    required: true
  apworld-name:
    description: The name of the apworld. This should only be set if the folder storing your apworld in the repository isn't the same
    default: ""
    required: true
  ap-version:
    description: The version of archipelago to use. This must match a refspec in the archipelago repository
    default: "latest"
    required: true
outputs:
  apworld:
    description: The path of the resulting apworld file
    value: ${{ steps.package.outputs.apworld }}
  apworld-name:
    description: The name of the apworld
    value: ${{ steps.package.outputs.apworld-name }}
runs:
  using: composite
  steps:
    - name: Clone the repo
      uses: actions/checkout@master
      if: ${{ inputs.checkout != 'false' }}

    - uses: Eijebong/ap-actions/setup-ap@main
      with:
        version: ${{ inputs.ap-version }}
        python-version: ${{ inputs.python-version }}

    - name: Package apworld
      id: package
      shell: bash
      run: |
        if [[ "${APWORLD_NAME}" == "" ]]; then
          if [[ "${APWORLD_PATH}" == *.apworld ]]; then
            export APWORLD_NAME=$(basename "${APWORLD_PATH}" .apworld)
          else
            export APWORLD_NAME=$(basename "${APWORLD_PATH}")
          fi
        fi

        mkdir -p /tmp/ap-output
        echo "apworld=/tmp/ap-output/${APWORLD_NAME}.apworld" >> ${GITHUB_OUTPUT}

        if [[ "${APWORLD_PATH}" == *.apworld ]]; then
          cp "${APWORLD_PATH}" /tmp/ap-output/${APWORLD_NAME}.apworld
        else
          cp -r "${APWORLD_PATH}" archipelago/worlds/${APWORLD_NAME}
          cd archipelago && uv run python Launcher.py "Build APWorlds"
          mv "build/apworlds/${APWORLD_NAME}.apworld" "/tmp/ap-output/${APWORLD_NAME}.apworld"
        fi

        echo "apworld-name=${APWORLD_NAME}" >> ${GITHUB_OUTPUT}
      env:
        APWORLD_PATH: ${{ inputs.path }}
        APWORLD_NAME: ${{ steps.copy.output.apworld-name }}
