name: Generate a template YAML for a given apworld
description: Setup a base archipelago installation and generate a default template for the given apworld
inputs:
  ap-version:
    description: The version of archipelago to use. This must match a refspec in the archipelago repository
    required: true
  python-version:
    description: The python version to use
    required: true
  apworld-path:
    description: The path to the apworld folder
    required: true
  apworld-name:
    description: The name of the apworld. This should only be set if the folder storing your apworld in the repository isn't the same
    type: string
    default: ""
outputs:
  template:
    description: The path to the generated template YAML
    value: ${{ steps.generate.outputs.path }}
runs:
  using: composite
  steps:
    - uses: Eijebong/ap-actions/package-apworld@main
      id: package
      with:
        path: ${{ inputs.apworld-path }}
        apworld-name: ${{ inputs.apworld-name }}

    - uses: Eijebong/ap-actions/setup-ap@main
      with:
        version: ${{ inputs.ap-version }}
        python-version: ${{ inputs.python-version }}

    - name: Copy apworld in custom worlds
      shell: bash
      run: |
        cp ${APWORLD_PATH} archipelago/custom_worlds/
      env:
        APWORLD_PATH: ${{ steps.package.outputs.apworld }}

    - name: Copy template generator
      shell: bash
      run: |
        cp ${GITHUB_ACTION_PATH}/generate_template.py archipelago/generate_template.py

    - name: Generate templates
      id: generate
      shell: bash
      run: |
        if [[ "${APWORLD_NAME}" == "" ]]; then
          export APWORLD_NAME=$(basename ${APWORLD_PATH%.apworld})
        fi

        cd archipelago && uv run python generate_template.py ${APWORLD_NAME}
        # The script unloads every world except the targeted one so there's only ever one template in the folder
        export TEMPLATE_PATH="$(ls templates/)"
        echo "path=archipelago/templates/${TEMPLATE_PATH}" >> ${GITHUB_OUTPUT}
      env:
        APWORLD_PATH: ${{ inputs.apworld-path }}
        APWORLD_NAME: ${{ inputs.apworld-name }}
